name: marquee_text
description: Scroll automatically when the child exceeds the width of the container.
version: 2.5.0+1
homepage: https://github.com/zh28/flutter-marquee-text

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
