name: marquee_text
description: Scroll automatically when the text exceeds the width of the container.
version: 2.0.0
homepage: https://github.com/zh28/flutter-marquee-text

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
