name: cd-action-test-publish
on:
  release:
    types: [published] 

jobs:
  publish-to-pub:
    runs-on: ubuntu-latest
    steps:
      - uses: zhcode-fun/flutter-marquee-text

      - name: 🔧 Setup Dart SDK
        uses: dart-lang/setup-dart@v2.12.3 # setups dart sdk on this machine
      - name: 🚀Publish
        uses: RatakondalaArun/pub.dev-cd@v1
        with:
          creditionals: ${{secrets.PUB_CREDITIONALS}}
          # package_path: packages/subpackage
